chatroom/urls.py
from django.conf.urls import url, include
from django.contrib.auth.views import login, logout
from django.contrib.auth.decorators import login_required, user_passes_test

from .views import RoomDetail, RoomList, RoomSettings
from .views import CreateRoom, DeleteRoom
from .views import MemberList, AddMemberToRoom, RemoveMemberFromRoom
from .views import UserManager, CreateUser, DeleteUser


app_name = 'chatroom'
urlpatterns = [
    url(r'^$',
        login_required(RoomList.as_view()),
        name='room-list'),
    url(r'^rooms/createroom/$',
        user_passes_test(lambda u: u.is_superuser)(CreateRoom.as_view()),
        name='create-room'),
    url(r'^rooms/deleteroom/(?P<slug>[-\w]+)/$',
        user_passes_test(lambda u: u.is_superuser)(DeleteRoom.as_view()),
        name='delete-room'),
    url(r'^(?P<slug>[-\w]+)/$',
        login_required(RoomDetail.as_view()),
        name='room-detail'),
    url(r'^(?P<slug>[-\w]+)/settings/$',
        user_passes_test(lambda u: u.is_superuser)(RoomSettings.as_view()),
        name='room-settings'),


    url(r'^(?P<slug>[-\w]+)/members/$',
        login_required(MemberList.as_view()),
        name='member-list'),
    url(r'^(?P<slug>[-\w]+)/addmember/(?P<pk>[\d]+)/$',
        user_passes_test(lambda u: u.is_superuser)(AddMemberToRoom.as_view()),
        name='add-member'),
    url(r'^(?P<slug>[-\w]+)/removemember/(?P<pk>[\d]+)/$',
        user_passes_test(lambda u: u.is_superuser)(RemoveMemberFromRoom.as_view()),
        name='remove-member'),


    url(r'^accounts/login/$', 
        login,
       ),
    url(r'^accounts/logout/$',
        logout,
        {'next_page': '/'},
        name='logout'),

    url(r'^accounts/usermanager/$',
        login_required(UserManager.as_view()),
        name='user-manager'),
    url(r'^accounts/createuser/$',
        user_passes_test(lambda u: u.is_superuser)(CreateUser.as_view()),
        name='create-user'),
    url(r'^accounts/deleteuser/(?P<pk>[\d]+)/$',
        user_passes_test(lambda u: u.is_superuser)(DeleteUser.as_view()),
        name='delete-user'),
]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('chatroom.urls')),
]

chatroom/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify


class Room(models.Model):
    name = models.CharField(max_length=40, unique=True)
    slug = models.SlugField()
    members = models.ManyToManyField(User,
                                     related_name="rooms",
                                     limit_choices_to={'is_superuser':False},
                                    )

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Room, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('chatroom:room-detail', kwargs={"slug": self.slug})



class Message(models.Model):
    room = models.ForeignKey(Room, related_name="messages")
    user = models.ForeignKey(User)

    content = models.CharField(max_length=250)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['timestamp']

chatroom/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Room, Message

from django.utils.translation import ugettext, ugettext_lazy as _


class RoomForm(forms.ModelForm):
    name = forms.CharField(
        label=_("Name"),
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    members = forms.ModelMultipleChoiceField(
        queryset=User.objects.filter(is_superuser=False),
        widget=forms.SelectMultiple(attrs={'class': 'form-control'}),
        required=False,
    )


    class Meta:
        model = Room
        fields = ('name', 'members')

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super(RoomForm, self).__init__(*args, **kwargs)


class MessageForm(forms.ModelForm):
    content = forms.CharField(
        label=_("Content"),
        widget=forms.Textarea(attrs={'class': 'form-control input-chat',
                                     'rows': 3})
    )

    class Meta:
        model = Message
        fields = ('content',)

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super(MessageForm, self).__init__(*args, **kwargs)


class UserForm(forms.ModelForm):
    username = forms.CharField(
        label=_("Username"),
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )

    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super(UserForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class UploadFile(forms.Form):
    file = forms.FileField(
        label=_("Upload File To Create User"),
        widget=forms.FileInput(attrs={'class': 'form-contorl'}),
    )

chatroom/views.py
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.core.urlresolvers import reverse

from .models import Room, Message
from django.contrib.auth.models import User

from .forms import RoomForm, MessageForm, UserForm, UploadFile
from django.contrib.auth.forms import UserCreationForm

from django.views.generic import View, ListView, DetailView
from django.views.generic.edit import FormMixin, CreateView, DeleteView, UpdateView
from django.views.generic.list import BaseListView
from django.views.generic.detail import SingleObjectMixin

from django.core.exceptions import PermissionDenied


class RoomList(ListView):
    def get_user(self):
        return User.objects.get(username=self.request.user.username)

    def get_queryset(self):
        queryset = Room.objects.all()
        if not self.get_user().is_superuser:
            queryset = self.get_user().rooms.all()
        return queryset


class RoomDetail(FormMixin, DetailView):
    model = Room
    form_class = MessageForm

    def get_message_queryset(self):
        qs = self.get_object().messages.all()
        last = self.request.GET.get('last',0)
        if last:
            qs = qs.filter(pk__gt=last)
        return qs

    def get_success_url(self):
        return reverse('chatroom:room-detail', kwargs={'slug':self.get_object().slug})

    def get_context_data(self, **kwargs):
        context = super(RoomDetail, self).get_context_data(**kwargs)
        context['form'] = self.get_form()
        context['message'] = self.get_message_queryset()
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.room = Room.objects.get(slug=self.kwargs['slug'])
        form.save()
        return super(RoomDetail, self).form_valid(form)

    def get_template_names(self):
        template_names = super(RoomDetail, self).get_template_names()
        if self.request.is_ajax():
            template_names = 'chatroom/message.html'
        return template_names

    def dispatch(self, request, *args, **kwargs):
        members = self.get_object().members.all()
        if not request.user.is_superuser:
            if request.user not in members:
                raise PermissionDenied()
        return super(RoomDetail, self).dispatch(request, *args, **kwargs)


class RoomSettings(UpdateView):
    model = Room
    form_class = RoomForm


class CreateRoom(CreateView):
    model = Room
    form_class = RoomForm


class DeleteRoom(DeleteView):
    model = Room

    def get(self, request, *args, **kwargs):
        return self.post(self, request, *args, **kwargs)

    def get_success_url(self):
        return reverse('chatroom:room-list')


class MemberList(ListView):
    def get_template_names(self):
        template_names = 'chatroom/member_list.html'
        return template_names

    def get_not_members(self):
        qs = User.objects.exclude(rooms__slug__contains=self.kwargs['slug'])
        return qs.filter(is_superuser=False)

    def get_context_data(self, **kwargs):
        context = super(MemberList, self).get_context_data(**kwargs)
        context['not_members'] = self.get_not_members()
        context['room'] = self.get_room()
        return context

    def get_room(self):
        return Room.objects.get(slug=self.kwargs['slug'])

    def get_queryset(self):
        return self.get_room().members.exclude(username=self.request.user.username)


class AddMemberToRoom(SingleObjectMixin, View):
    model = User

    def get(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            return HttpResponseForbidden
        user = self.get_object()
        room = Room.objects.get(slug=self.kwargs['slug'])
        room.members.add(user)
        room.save()
        return HttpResponseRedirect(reverse('chatroom:room-detail',
                                            kwargs={'slug':self.kwargs['slug']}))


class RemoveMemberFromRoom(SingleObjectMixin, View):
    model = User

    def get(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            return HttpResponseForbidden
        user = self.get_object()
        room = Room.objects.get(slug=self.kwargs['slug'])
        room.members.remove(user)
        room.save()
        return HttpResponseRedirect(reverse('chatroom:room-detail',
                                            kwargs={'slug':self.kwargs['slug']}))


class UserManager(FormMixin, ListView):
    form_class = UploadFile


    def get_queryset(self):
        return User.objects.filter(is_superuser=False)

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            raise PermissionDenied()
        return super(UserManager, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('chatroom:user-manager')

    def get_context_data(self, **kwargs):
        context = super(UserManager, self).get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def handle_uploaded_file(self, upload_file):
        for line in upload_file:
            for i, char in enumerate(line, 1):
                if char == " ":
                    username = line[:i].rstrip()
                    password = line[i+1:].strip()
                    break
            if User.objects.filter(username=username).exists():
                pass
            else:
                user = User.objects.create_user(username=username)
                user.set_password(password)
                user.save()

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            self.handle_uploaded_file(request.FILES['file'])
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class DeleteUser(DeleteView):
    model = User

    def get(self, request, *args, **kwargs):
        return self.post(self, request, *args, **kwargs)

    def get_success_url(self):
        return reverse('chatroom:user-manager')


class CreateUser(CreateView):
    model = User
    form_class = UserForm

    def get_success_url(self):
        return reverse('chatroom:user-manager')

templates/chatroom/member_list.html
  <tbody>
  {% for user in object_list %}
    <tr>
      <td></td>
      <td>{{ user.username }}</td>
      {% if request.user.is_superuser %}
      <td>
        <a href="{% url 'chatroom:remove-member' slug=room.slug pk=user.id %}">
        <i class="fa fa-times" title="remove" aria-hidden="true"></i>
        </a>
      </td>
      {% endif %}
    <tr>
  {% endfor %}

  {% if request.user.is_superuser %}
    {% for user in not_members %}
    <tr>
      <td></td>
      <td>{{ user.username }}</td>
      <td>
        <a href="{% url 'chatroom:add-member' slug=room.slug pk=user.id %}">
        <i class="fa fa-plus" title="invite" aria-hidden="true"></i>
        </a>
      </td>
    </tr>
    {% endfor %}
  {% endif %}
  <tbody>

templates/chatroom/message.html
{% load tz %}
{% for obj in message %}
  <li class='message' id="chat_message_{{obj.pk}}" data-id='{{obj.pk}}'>
  <p><span>[{{ obj.timestamp|timezone:'Asia/Taipei'|date:'Y-m-d H:i A' }}] {{ obj.user.username|title }}</span>&nbsp:&nbsp&nbsp<span>{{ obj.content }}</span></p>
  </li>
{% endfor %}

templates/chatroom/room_detail.html
{% extends 'base.html' %}

{% block content %}
<section>
  <div class="container">
    <div class="well">
      <div class="row">
        <div class="col-md-12">
          <div class="header">
            <h1>{{ object.name}}&nbsp&nbsp
              {% if request.user.is_superuser %}
              <a href="{% url 'chatroom:room-settings' object.slug %}"><i class="fa fa-cogs" title="settings" aria-hidden="true"></i></a>
              {% endif %}
              <a href="{% url 'chatroom:room-list' %}"><i class="fa fa-home" title="home" aria-hidden="true"></i></a>
            </h1>
          </div>
        </div>
        <div class="col-md-9">
          <div class="chatview">
            <ul id="chatlog">
            {% include 'chatroom/message.html' %}
            </ul>
          </div>
          <div class="chatform">
            <form method="post" id="create_message">
            {% csrf_token %}
            <div class="form-group">
              {{form.content}}
              <input type='submit' class="btn btn-default btn-raised btn-lg btn-chat" value='Submit'>
            </div>
            </form>
          </div>
        </div>

        <div class="col-md-3">
         <div class="userlist">
           <div class="currentuser">
             <p class="text-center">Hello,&nbsp&nbsp{{ request.user.username|title }}</p>
           </div>
           <div class="memberlist">
            <table id="memberlog">
            </table>
           </div>
         </div>
        </div>
      </div>
    </div>
  </div>
</section>



{% endblock %}

{% block js %}
<script type='text/javascript'>

var update_user = function(){
  $.ajax({
    url: "{% url 'chatroom:member-list' object.slug %}",
    success: function(data) {
      $('#memberlog').html(data);
    }
  });
};

var update_chat = function(){
  var last_msg_id = $('#chatlog > .message').last().data('id');
  $.ajax({
    url: "{% url 'chatroom:room-detail' object.slug %}",
    data: {last: last_msg_id},
    success: function(data) {
      $('#chatlog').append(data);
      $('.chatview').scrollTop( $('.chatview')[0].scrollHeight  );
    }
  });
};

var clear_form = function(){
  $('#create_message').each(function(){this.reset();});
}

var post_message = function(event){
  event.preventDefault();
  var form = $(this);

  $.ajax({
    url : form.attr('action'),
    type : form.attr('method'),
    data : form.serialize(),
  });
  update_chat();
  clear_form();
  $('#id_content').focus();
}

$(function (){
  update_user();
  setInterval(update_user, 4000);
  setInterval(update_chat, 2000);
  $('textarea').on('keydown', function(event) {
    if (event.keyCode == 13) {
      if (!event.shiftKey) {
        $('#create_message').submit();
      };
    };
  });
  $('.chatview').scrollTop( $('.chatview')[0].scrollHeight  );
  $('#create_message').on('submit', post_message);
  $('#id_content').focus();
});


</script>
{% endblock %}

templates/chatroom/room_form.html
{% extends 'base.html' %}
{% block title %}
{{ object.name }}&nbsp&nbspSettings
{% endblock %}

{% block content %}
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="well">
          <legend>{{ object.name }}&nbsp&nbspSettings</legend>
          <form enctype="multipart/form-data" method="POST" class="">
          {% csrf_token %}

            <div class="form-group label-floating">
              <label for="{{ form.name.id_for_label }}"
                class="control-label">{{ form.name.label_tag }}</label>
              {{ form.name }}
              <span class="help-block">{{ form.name.help_text|safe }}</span>
            </div>
            {{ form.name.errors }}

            <div class="form-group">
              <label for="{{ form.members.id_for_label }}" class="control-label">{{ form.members.label_tag }}</label>
                {{ form.members }}
              <span class="help-block">{{ form.members.help_text|safe }}</span>
            </div>
            {{ form.members.errors }}

            <div class="form-group">
              <a href="javascript:history.back(1)" class="btn btn-default">Cancel</a>
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/chatroom/room_list.html
{% extends 'base.html' %}

{% block content %}
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="well">
          <div class="header">
            <h1>ChatRoom List&nbsp&nbsp
              {% if request.user.is_superuser %}
              <span data-placement="top" data-toggle="tooltip" title="UserManager">
                <a class="btn btn-primary btn-xs" href="{% url 'chatroom:user-manager' %}"><i class="fa fa-users fa-2x"></i></a>
              </span>
              {% endif %}
              <a class="btn btn-default btn-xs" href="{% url 'chatroom:logout' %}"><i class="fa fa-sign-out fa-2x"></i></a>
            </h1>
          </div>
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th><h3>#</h3></th>
                <th><h3>Room Name</h3></th>
                <th><h3>Member Number</h3></th>
                <th><h3>Join</h3></th>
                {% if request.user.is_superuser %}
                <th><h3>Settings</h3></th>
                <th><h3>Delete</h3></th>
                {% endif %}
              </tr>
            </thead>
            <tbody>
            {% for room in object_list %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ room.name }}</td>
                <td>{{ room.members.count }}</td>
                <td>
                  <a class="btn btn-warning btn-raised" href="{% url 'chatroom:room-detail' room.slug %}">Enter</a>
                </td>
                {% if request.user.is_superuser %}
                <td>
                  <p data-placement="top" data-toggle="tooltip" title="Edit">
                    <a class="btn btn-primary btn-xs" href="{% url 'chatroom:room-settings' room.slug %}"><i class="fa fa-cogs fa-2x"></i></a>
                  </p>
                </td>
                <td>
                  <p data-placement="top" data-toggle="tooltip" title="Delete">
                  <a class="btn btn-danger btn-xs" href="{% url 'chatroom:delete-room' room.slug %}"><i class="fa fa-trash fa-2x"></i></a>
                  </p>
                </td>
                {% endif %}
              </tr>
            {% endfor %}
            </tbody>
          </table>
          {% if request.user.is_superuser %}
          <a href="{% url 'chatroom:create-room' %}" class="btn btn-default btn-lg btn-block btn-raised"><i class="fa fa-plus" aria-hidden="true">Create New Room</i></a>
          {% endif %}

        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}